### ISSUE TITLE
Allow access to T_cam0unrect_velo

### ISSUE THREAD

**Issue by kampelmuehler** [utiasSTARS/pykitti#15]
Hi,

I'd suggest making the rigid transformation from velodyne coordinates to unrectified cam0 coordinates accessible by adding 
    data['Tr_velo_to_cam'] = T_cam0unrect_velo
in line 142 in raw.py 

Cheers,
Moritz

**Comment by leeclemnet** [comment]
It's now exposed as data['T_cam0_velo_unrect'] (see https://github.com/utiasSTARS/pykitti/commit/b313a094b18afd9fe20067ed3f68fcafcc325e65). Updated on pypi as well.
