### ISSUE TITLE
How to convert velodyne coordinates to world coordinates?

### ISSUE THREAD

**Issue by jaskaran1** [utiasSTARS/pykitti#16]
Hello,

How does one convert from Velodyne to world coordinates using GPS/IMU?

As a first step,
I was able to go from Velodyne to the IMU coordinate system(which is still in the car frame). 

Now using these coordinates, how do I get to the world coordinates?

**Comment by leeclemnet** [comment]
The IMU-to-world transformations are provided through the oxts property as T_w_imu. If you have points in the IMU coordinate system, you just have to pre-multiply them by T_w_imu to transform them into the world coordinate system. Check the readme for an example of how to access the IMU-to-world transformations.

**Comment by jaskaran1** [comment]
I realized later that w in T_w_imu means world frame.
Thanks for the clarification.
