### ISSUE TITLE
No T_imu_velo

### ISSUE THREAD

**Issue by jaskaran1** [utiasSTARS/pykitti#17]
I could find only the T_velo_imu in data.calib but didn't find T_imu_velo. 

So, right now I'm using this 
https://mathematica.stackexchange.com/questions/106257/how-do-i-get-the-inverse-of-a-homogeneous-transformation-matrix

to get the T_imu_velo.

It would be helpful, if you could add this. Or I can send you a pull request later.

**Comment by leeclemnet** [comment]
Why not use `T_imu_velo = numpy.linalg.inv(T_velo_imu)` to do this? You should get the same result.
