### ISSUE TITLE
Mistake in Documentation?!

### ISSUE THREAD

**Issue by varun-bankiti** [utiasSTARS/pykitti#20]
Hello,

Is [this](https://github.com/utiasSTARS/pykitti/blob/master/pykitti/raw.py#L222) a mistake?
Shouldn't it be ` # Load the rigid transformation from IMU to velodyne`. 
LMK if I understood it wrong.

Thanks.

**Comment by leeclemnet** [comment]
Oops, good catch. I've updated the comment (https://github.com/utiasSTARS/pykitti/commit/08b3199d8033efb9b3785859f52ac5efa35fbf61).
