### ISSUE TITLE
Cannot import tracking (Not listed in __init__.py)

### ISSUE THREAD

**Issue by tuxbotix** [utiasSTARS/pykitti#41]
I wanted to import the tracking class but was unable to do so; I realized tracking module is a recent-ish addition: Is there a reason not to include this yet? If not, it would be nice to enable it.

P.S. Thank you for releasing this toolkit, saved a lot of time and headaches. ^_^

Cheers!

**Comment by leeclemnet** [comment]
Oops, I guess I didn't check that when I merged the PR. I just pushed version 0.3.1 to pypi, which should solve this problem. :)

**Comment by tuxbotix** [comment]
Thanks ^_^ It's not exactly stable yet, I fixed some stuff locally for the moment, Will do a  PR once fixed.
