### ISSUE TITLE
caculate Tr_velo_to_cam

### ISSUE THREAD

**Issue by enting8696** [utiasSTARS/pykitti#64]
if i have corresponding velodyne coordinate point [x,y,z] and pixel coordinate [u,v]
can i use  `x = P2 * R0_rect * Tr_velo_to_cam * y` to find out Tr_velo_to_cam
beacause i know x,P2,R0_rect ,y

can someone give me some advice?

**Comment by immaturehaan** [comment]
hello, can you find Tr_velo_to_cam?
